#!/bin/sh

set -e

# Create a "kannel" user. This has modeled after the code in the postfix.deb
# postinst. We first try to set the ownership of /var/log/kannel. If that
# fails, we create the user and re-try. If that still fails, we abort.

if chown kannel.root /var/log/kannel 2>/dev/null
then
    :
elif adduser --system --home /var/log/kannel --group kannel
then
    chown kannel.root /var/log/kannel
fi
