#!/bin/sh
#
# daily-patch - generate and e-mail the daily patch for Kannel
#
# DO NOT RUN THIS SCRIPT, unless you know the recipient and the CVS maintainer
# want you to.
#
# Make a "daily patch", or actually just a patch from the previous time
# this script was run.
#
# Lars Wirzenius <liw@wapit.com>
#

set -e

addr=""
CVSROOT=":pserver:anonymoua@cvs.kannel.org:/home/cvs"

temp=/tmp/daily-patch.$$

for module in "$@"
do
	cvs -Q -d$CVSROOT rtag -F -a -D now new_daily_patch_tag $module
	cvs -Q -d$CVSROOT rdiff -r daily_patch_tag -r new_daily_patch_tag \
		-u $module > $temp
	if [ -s "$temp" ]
	then
		cat $temp
	else
		echo "No changes in $module since yesterday."
	fi | mail -s "Daily patch: $module" $addr
	rm -f $temp

	cvs -Q -d$CVSROOT rtag -F -a -r new_daily_patch_tag daily_patch_tag \
		$module
done
