#!/bin/sh
#
# Create distribution files.
#
# Lars Wirzenius <liw@wapit.com>

set -e

version="$1"
tag=version_`echo $version | tr .- __`
base=gateway-$version

rm -rf $base $base.tar.gz README-$version design-$version design-$version.ps
cvs -Q export -r $tag -d $base gateway
if fgrep "$version" $base/VERSION >/dev/null
then
	:
else
	echo "Oops, VERSION does not match."
	exit 1
fi

tar -c -z -f $base.tar.gz $base
echo "Only building $base.tar.gz."
exit 1
zip -9qr $base.zip $base/*

(cd $base && ./configure --enable-docs >/dev/null && make -s docs)

cp -a $base/doc/arch arch-$version
tar -c -z -f arch-$version.tar.gz arch-$version/*
zip -9qr arch-$version.zip arch-$version/*
cp $base/NEWS NEWS-$version
cp $base/README README-$version
cp $base/ChangeLog ChangeLog-$version
