#!/bin/sh
#
# Create distribution files.
#
# Lars Wirzenius <liw@wapit.com>

set -e

version="$1"
tag=version_`echo $version | tr .- __`
base=gateway-$version

rm -rf $base $base.tar.gz README-$version design-$version design-$version.ps
cvs -Q export -r $tag -d $base gateway
(cd $base && ./configure) > /dev/null
# make -C $base/doc -s
tar -c -z -f $base.tar.gz $base
zip -9qr $base.zip $base/*
# cp -a $base/doc/design.html design-$version
# zip -9qr design-$version.zip design-$version/*
# cp $base/doc/design.ps design-$version.ps
[ -e $base/Release-$version ] && cp $base/Release-$version .
[ -e $base/README ] && cp $base/README README-$version
[ -e $base/ChangeLog ] && cp $base/ChangeLog ChangeLog-$version
